"""empty message

Revision ID: 13b3cd330e0f
Revises: bbf4eef302d6
Create Date: 2025-08-20 23:46:21.062256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b3cd330e0f'
down_revision = 'bbf4eef302d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('information_stored')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_people', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite_planets', sa.Integer(), nullable=True))
        batch_op.drop_column('favorite_the_planet_id')
        batch_op.drop_column('favorite_the_character_id')
        batch_op.drop_column('favorite_planets_id')
        batch_op.drop_column('favorite_characters_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_characters_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favorite_planets_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favorite_the_character_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favorite_the_planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('favorite_planets')
        batch_op.drop_column('favorite_people')

    op.create_table('information_stored',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], name='information_stored_favorites_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='information_stored_pkey')
    )
    op.drop_table('planet')
    op.drop_table('people')
    # ### end Alembic commands ###
