"""empty message

Revision ID: 86129c1b3d53
Revises: 13b3cd330e0f
Create Date: 2025-08-20 23:48:53.516227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86129c1b3d53'
down_revision = '13b3cd330e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_people_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite_planet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planet', ['favorite_planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['favorite_people_id'], ['id'])
        batch_op.drop_column('favorite_planets')
        batch_op.drop_column('favorite_people')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_people', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favorite_planets', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite_planet_id')
        batch_op.drop_column('favorite_people_id')

    # ### end Alembic commands ###
